/* soapServer.cpp
   Generated by gSOAP 2.7.12 from ..\gSoapInput\TpcServerSoap.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.7.12 2022-08-12 12:59:19 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetInterfaceVersion"))
		return soap_serve_ns__GetInterfaceVersion(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:ResetConfiguration"))
		return soap_serve_ns__ResetConfiguration(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:AcquireDeviceLock"))
		return soap_serve_ns__AcquireDeviceLock(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:ReleaseDeviceLock"))
		return soap_serve_ns__ReleaseDeviceLock(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetClusterConfiguration"))
		return soap_serve_ns__GetClusterConfiguration(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SetClusterConfiguration"))
		return soap_serve_ns__SetClusterConfiguration(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetHardwareInfo"))
		return soap_serve_ns__GetHardwareInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SetOneParameter"))
		return soap_serve_ns__SetOneParameter(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SetMultipleParameters"))
		return soap_serve_ns__SetMultipleParameters(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetAllCurrentParameters"))
		return soap_serve_ns__GetAllCurrentParameters(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetAllPreviousParameters"))
		return soap_serve_ns__GetAllPreviousParameters(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SetAttributes"))
		return soap_serve_ns__SetAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetAllCurrentAttributes"))
		return soap_serve_ns__GetAllCurrentAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetAllPreviousAttributes"))
		return soap_serve_ns__GetAllPreviousAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetSerTrgProtocol"))
		return soap_serve_ns__GetSerTrgProtocol(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:ResetSerTrg"))
		return soap_serve_ns__ResetSerTrg(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SetI2CTrigger"))
		return soap_serve_ns__SetI2CTrigger(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetI2CTrigger"))
		return soap_serve_ns__GetI2CTrigger(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SetCANTrigger"))
		return soap_serve_ns__SetCANTrigger(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetCANTrigger"))
		return soap_serve_ns__GetCANTrigger(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetAllCurrentAssociations"))
		return soap_serve_ns__GetAllCurrentAssociations(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetAllPreviousAssociations"))
		return soap_serve_ns__GetAllPreviousAssociations(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SetAssociations"))
		return soap_serve_ns__SetAssociations(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetGPSLogList"))
		return soap_serve_ns__GetGPSLogList(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:WriteDev"))
		return soap_serve_ns__WriteDev(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:ReadDev"))
		return soap_serve_ns__ReadDev(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:ReadWriteTwi"))
		return soap_serve_ns__ReadWriteTwi(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:PrepareStart"))
		return soap_serve_ns__PrepareStart(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SetStartInfo"))
		return soap_serve_ns__SetStartInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:ExecuteCommand"))
		return soap_serve_ns__ExecuteCommand(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:StartCalibration"))
		return soap_serve_ns__StartCalibration(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetStatus"))
		return soap_serve_ns__GetStatus(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:WaitForStatusChange"))
		return soap_serve_ns__WaitForStatusChange(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:LeaveWaitStatus"))
		return soap_serve_ns__LeaveWaitStatus(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetMetadata"))
		return soap_serve_ns__GetMetadata(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetAllYMetadata"))
		return soap_serve_ns__GetAllYMetadata(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetData"))
		return soap_serve_ns__GetData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SendServerCustomCommand"))
		return soap_serve_ns__SendServerCustomCommand(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:LoadAutosequence"))
		return soap_serve_ns__LoadAutosequence(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:StartAutoSequence"))
		return soap_serve_ns__StartAutoSequence(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:StopAutoSequence"))
		return soap_serve_ns__StopAutoSequence(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetAutoSequence"))
		return soap_serve_ns__GetAutoSequence(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SetDeviceSettings"))
		return soap_serve_ns__SetDeviceSettings(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetFreeDiskSpace"))
		return soap_serve_ns__GetFreeDiskSpace(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetMACAddress"))
		return soap_serve_ns__GetMACAddress(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetInterfaceVersion(struct soap *soap)
{	struct ns__GetInterfaceVersion soap_tmp_ns__GetInterfaceVersion;
	struct ns__GetInterfaceVersionResponse soap_tmp_ns__GetInterfaceVersionResponse;
	soap_default_ns__GetInterfaceVersionResponse(soap, &soap_tmp_ns__GetInterfaceVersionResponse);
	soap_default_ns__GetInterfaceVersion(soap, &soap_tmp_ns__GetInterfaceVersion);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetInterfaceVersion(soap, &soap_tmp_ns__GetInterfaceVersion, "ns:GetInterfaceVersion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetInterfaceVersion(soap, soap_tmp_ns__GetInterfaceVersionResponse.version);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetInterfaceVersionResponse(soap, &soap_tmp_ns__GetInterfaceVersionResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetInterfaceVersionResponse(soap, &soap_tmp_ns__GetInterfaceVersionResponse, "ns:GetInterfaceVersionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetInterfaceVersionResponse(soap, &soap_tmp_ns__GetInterfaceVersionResponse, "ns:GetInterfaceVersionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__ResetConfiguration(struct soap *soap)
{	struct ns__ResetConfiguration soap_tmp_ns__ResetConfiguration;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__ResetConfiguration(soap, &soap_tmp_ns__ResetConfiguration);
	soap->encodingStyle = "";
	if (!soap_get_ns__ResetConfiguration(soap, &soap_tmp_ns__ResetConfiguration, "ns:ResetConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__ResetConfiguration(soap, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__AcquireDeviceLock(struct soap *soap)
{	struct ns__AcquireDeviceLock soap_tmp_ns__AcquireDeviceLock;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__AcquireDeviceLock(soap, &soap_tmp_ns__AcquireDeviceLock);
	soap->encodingStyle = "";
	if (!soap_get_ns__AcquireDeviceLock(soap, &soap_tmp_ns__AcquireDeviceLock, "ns:AcquireDeviceLock", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__AcquireDeviceLock(soap, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__ReleaseDeviceLock(struct soap *soap)
{	struct ns__ReleaseDeviceLock soap_tmp_ns__ReleaseDeviceLock;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__ReleaseDeviceLock(soap, &soap_tmp_ns__ReleaseDeviceLock);
	soap->encodingStyle = "";
	if (!soap_get_ns__ReleaseDeviceLock(soap, &soap_tmp_ns__ReleaseDeviceLock, "ns:ReleaseDeviceLock", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__ReleaseDeviceLock(soap, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetClusterConfiguration(struct soap *soap)
{	struct ns__GetClusterConfiguration soap_tmp_ns__GetClusterConfiguration;
	struct ns__ClusterConfiguration clusters;
	soap_default_ns__ClusterConfiguration(soap, &clusters);
	soap_default_ns__GetClusterConfiguration(soap, &soap_tmp_ns__GetClusterConfiguration);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetClusterConfiguration(soap, &soap_tmp_ns__GetClusterConfiguration, "ns:GetClusterConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetClusterConfiguration(soap, clusters);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__ClusterConfiguration(soap, &clusters);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__ClusterConfiguration(soap, &clusters, "ns:ClusterConfiguration", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__ClusterConfiguration(soap, &clusters, "ns:ClusterConfiguration", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SetClusterConfiguration(struct soap *soap)
{	struct ns__SetClusterConfiguration soap_tmp_ns__SetClusterConfiguration;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__SetClusterConfiguration(soap, &soap_tmp_ns__SetClusterConfiguration);
	soap->encodingStyle = "";
	if (!soap_get_ns__SetClusterConfiguration(soap, &soap_tmp_ns__SetClusterConfiguration, "ns:SetClusterConfiguration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SetClusterConfiguration(soap, soap_tmp_ns__SetClusterConfiguration.clusters, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetHardwareInfo(struct soap *soap)
{	struct ns__GetHardwareInfo soap_tmp_ns__GetHardwareInfo;
	struct ns__HardwareInfo hardwareInfo;
	soap_default_ns__HardwareInfo(soap, &hardwareInfo);
	soap_default_ns__GetHardwareInfo(soap, &soap_tmp_ns__GetHardwareInfo);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetHardwareInfo(soap, &soap_tmp_ns__GetHardwareInfo, "ns:GetHardwareInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetHardwareInfo(soap, hardwareInfo);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__HardwareInfo(soap, &hardwareInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__HardwareInfo(soap, &hardwareInfo, "ns:HardwareInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__HardwareInfo(soap, &hardwareInfo, "ns:HardwareInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SetOneParameter(struct soap *soap)
{	struct ns__SetOneParameter soap_tmp_ns__SetOneParameter;
	struct ns__SetOneParameterResult result;
	soap_default_ns__SetOneParameterResult(soap, &result);
	soap_default_ns__SetOneParameter(soap, &soap_tmp_ns__SetOneParameter);
	soap->encodingStyle = "";
	if (!soap_get_ns__SetOneParameter(soap, &soap_tmp_ns__SetOneParameter, "ns:SetOneParameter", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SetOneParameter(soap, soap_tmp_ns__SetOneParameter.boardAddress, soap_tmp_ns__SetOneParameter.inputNumber, soap_tmp_ns__SetOneParameter.parameterIndex, soap_tmp_ns__SetOneParameter.value, result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__SetOneParameterResult(soap, &result);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__SetOneParameterResult(soap, &result, "ns:SetOneParameterResult", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__SetOneParameterResult(soap, &result, "ns:SetOneParameterResult", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SetMultipleParameters(struct soap *soap)
{	struct ns__SetMultipleParameters soap_tmp_ns__SetMultipleParameters;
	struct ns__SetMultipleParametersResponse soap_tmp_ns__SetMultipleParametersResponse;
	soap_default_ns__SetMultipleParametersResponse(soap, &soap_tmp_ns__SetMultipleParametersResponse);
	soap_default_ns__SetMultipleParameters(soap, &soap_tmp_ns__SetMultipleParameters);
	soap->encodingStyle = "";
	if (!soap_get_ns__SetMultipleParameters(soap, &soap_tmp_ns__SetMultipleParameters, "ns:SetMultipleParameters", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SetMultipleParameters(soap, soap_tmp_ns__SetMultipleParameters.parameters, soap_tmp_ns__SetMultipleParametersResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__SetMultipleParametersResponse(soap, &soap_tmp_ns__SetMultipleParametersResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__SetMultipleParametersResponse(soap, &soap_tmp_ns__SetMultipleParametersResponse, "ns:SetMultipleParametersResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__SetMultipleParametersResponse(soap, &soap_tmp_ns__SetMultipleParametersResponse, "ns:SetMultipleParametersResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetAllCurrentParameters(struct soap *soap)
{	struct ns__GetAllCurrentParameters soap_tmp_ns__GetAllCurrentParameters;
	struct ns__GetAllCurrentParametersResponse soap_tmp_ns__GetAllCurrentParametersResponse;
	soap_default_ns__GetAllCurrentParametersResponse(soap, &soap_tmp_ns__GetAllCurrentParametersResponse);
	soap_default_ns__GetAllCurrentParameters(soap, &soap_tmp_ns__GetAllCurrentParameters);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetAllCurrentParameters(soap, &soap_tmp_ns__GetAllCurrentParameters, "ns:GetAllCurrentParameters", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetAllCurrentParameters(soap, soap_tmp_ns__GetAllCurrentParametersResponse.parameters);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetAllCurrentParametersResponse(soap, &soap_tmp_ns__GetAllCurrentParametersResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetAllCurrentParametersResponse(soap, &soap_tmp_ns__GetAllCurrentParametersResponse, "ns:GetAllCurrentParametersResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetAllCurrentParametersResponse(soap, &soap_tmp_ns__GetAllCurrentParametersResponse, "ns:GetAllCurrentParametersResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetAllPreviousParameters(struct soap *soap)
{	struct ns__GetAllPreviousParameters soap_tmp_ns__GetAllPreviousParameters;
	struct ns__GetAllPreviousParametersResponse soap_tmp_ns__GetAllPreviousParametersResponse;
	soap_default_ns__GetAllPreviousParametersResponse(soap, &soap_tmp_ns__GetAllPreviousParametersResponse);
	soap_default_ns__GetAllPreviousParameters(soap, &soap_tmp_ns__GetAllPreviousParameters);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetAllPreviousParameters(soap, &soap_tmp_ns__GetAllPreviousParameters, "ns:GetAllPreviousParameters", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetAllPreviousParameters(soap, soap_tmp_ns__GetAllPreviousParameters.currentMeasurementNumber, soap_tmp_ns__GetAllPreviousParametersResponse.parameters);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetAllPreviousParametersResponse(soap, &soap_tmp_ns__GetAllPreviousParametersResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetAllPreviousParametersResponse(soap, &soap_tmp_ns__GetAllPreviousParametersResponse, "ns:GetAllPreviousParametersResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetAllPreviousParametersResponse(soap, &soap_tmp_ns__GetAllPreviousParametersResponse, "ns:GetAllPreviousParametersResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SetAttributes(struct soap *soap)
{	struct ns__SetAttributes soap_tmp_ns__SetAttributes;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__SetAttributes(soap, &soap_tmp_ns__SetAttributes);
	soap->encodingStyle = "";
	if (!soap_get_ns__SetAttributes(soap, &soap_tmp_ns__SetAttributes, "ns:SetAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SetAttributes(soap, soap_tmp_ns__SetAttributes.values, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetAllCurrentAttributes(struct soap *soap)
{	struct ns__GetAllCurrentAttributes soap_tmp_ns__GetAllCurrentAttributes;
	struct ns__GetAllCurrentAttributesResponse soap_tmp_ns__GetAllCurrentAttributesResponse;
	soap_default_ns__GetAllCurrentAttributesResponse(soap, &soap_tmp_ns__GetAllCurrentAttributesResponse);
	soap_default_ns__GetAllCurrentAttributes(soap, &soap_tmp_ns__GetAllCurrentAttributes);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetAllCurrentAttributes(soap, &soap_tmp_ns__GetAllCurrentAttributes, "ns:GetAllCurrentAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetAllCurrentAttributes(soap, soap_tmp_ns__GetAllCurrentAttributesResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetAllCurrentAttributesResponse(soap, &soap_tmp_ns__GetAllCurrentAttributesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetAllCurrentAttributesResponse(soap, &soap_tmp_ns__GetAllCurrentAttributesResponse, "ns:GetAllCurrentAttributesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetAllCurrentAttributesResponse(soap, &soap_tmp_ns__GetAllCurrentAttributesResponse, "ns:GetAllCurrentAttributesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetAllPreviousAttributes(struct soap *soap)
{	struct ns__GetAllPreviousAttributes soap_tmp_ns__GetAllPreviousAttributes;
	struct ns__GetAllPreviousAttributesResponse soap_tmp_ns__GetAllPreviousAttributesResponse;
	soap_default_ns__GetAllPreviousAttributesResponse(soap, &soap_tmp_ns__GetAllPreviousAttributesResponse);
	soap_default_ns__GetAllPreviousAttributes(soap, &soap_tmp_ns__GetAllPreviousAttributes);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetAllPreviousAttributes(soap, &soap_tmp_ns__GetAllPreviousAttributes, "ns:GetAllPreviousAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetAllPreviousAttributes(soap, soap_tmp_ns__GetAllPreviousAttributes.currentMeasurementNumber, soap_tmp_ns__GetAllPreviousAttributesResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetAllPreviousAttributesResponse(soap, &soap_tmp_ns__GetAllPreviousAttributesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetAllPreviousAttributesResponse(soap, &soap_tmp_ns__GetAllPreviousAttributesResponse, "ns:GetAllPreviousAttributesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetAllPreviousAttributesResponse(soap, &soap_tmp_ns__GetAllPreviousAttributesResponse, "ns:GetAllPreviousAttributesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetSerTrgProtocol(struct soap *soap)
{	struct ns__GetSerTrgProtocol soap_tmp_ns__GetSerTrgProtocol;
	struct ns__GetSerTrgProtocolResponse soap_tmp_ns__GetSerTrgProtocolResponse;
	soap_default_ns__GetSerTrgProtocolResponse(soap, &soap_tmp_ns__GetSerTrgProtocolResponse);
	soap_default_ns__GetSerTrgProtocol(soap, &soap_tmp_ns__GetSerTrgProtocol);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetSerTrgProtocol(soap, &soap_tmp_ns__GetSerTrgProtocol, "ns:GetSerTrgProtocol", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetSerTrgProtocol(soap, soap_tmp_ns__GetSerTrgProtocol.boardAddress, soap_tmp_ns__GetSerTrgProtocolResponse.prot);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetSerTrgProtocolResponse(soap, &soap_tmp_ns__GetSerTrgProtocolResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetSerTrgProtocolResponse(soap, &soap_tmp_ns__GetSerTrgProtocolResponse, "ns:GetSerTrgProtocolResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetSerTrgProtocolResponse(soap, &soap_tmp_ns__GetSerTrgProtocolResponse, "ns:GetSerTrgProtocolResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__ResetSerTrg(struct soap *soap)
{	struct ns__ResetSerTrg soap_tmp_ns__ResetSerTrg;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__ResetSerTrg(soap, &soap_tmp_ns__ResetSerTrg);
	soap->encodingStyle = "";
	if (!soap_get_ns__ResetSerTrg(soap, &soap_tmp_ns__ResetSerTrg, "ns:ResetSerTrg", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__ResetSerTrg(soap, soap_tmp_ns__ResetSerTrg.boardAddress, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SetI2CTrigger(struct soap *soap)
{	struct ns__SetI2CTrigger soap_tmp_ns__SetI2CTrigger;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__SetI2CTrigger(soap, &soap_tmp_ns__SetI2CTrigger);
	soap->encodingStyle = "";
	if (!soap_get_ns__SetI2CTrigger(soap, &soap_tmp_ns__SetI2CTrigger, "ns:SetI2CTrigger", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SetI2CTrigger(soap, soap_tmp_ns__SetI2CTrigger.boardAddress, soap_tmp_ns__SetI2CTrigger.settings, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetI2CTrigger(struct soap *soap)
{	struct ns__GetI2CTrigger soap_tmp_ns__GetI2CTrigger;
	struct ns__I2CTriggerSettings settings;
	soap_default_ns__I2CTriggerSettings(soap, &settings);
	soap_default_ns__GetI2CTrigger(soap, &soap_tmp_ns__GetI2CTrigger);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetI2CTrigger(soap, &soap_tmp_ns__GetI2CTrigger, "ns:GetI2CTrigger", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetI2CTrigger(soap, soap_tmp_ns__GetI2CTrigger.boardAddress, settings);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__I2CTriggerSettings(soap, &settings);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__I2CTriggerSettings(soap, &settings, "ns:I2CTriggerSettings", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__I2CTriggerSettings(soap, &settings, "ns:I2CTriggerSettings", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SetCANTrigger(struct soap *soap)
{	struct ns__SetCANTrigger soap_tmp_ns__SetCANTrigger;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__SetCANTrigger(soap, &soap_tmp_ns__SetCANTrigger);
	soap->encodingStyle = "";
	if (!soap_get_ns__SetCANTrigger(soap, &soap_tmp_ns__SetCANTrigger, "ns:SetCANTrigger", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SetCANTrigger(soap, soap_tmp_ns__SetCANTrigger.boardAddress, soap_tmp_ns__SetCANTrigger.settings, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetCANTrigger(struct soap *soap)
{	struct ns__GetCANTrigger soap_tmp_ns__GetCANTrigger;
	struct ns__CANTriggerSettings settings;
	soap_default_ns__CANTriggerSettings(soap, &settings);
	soap_default_ns__GetCANTrigger(soap, &soap_tmp_ns__GetCANTrigger);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetCANTrigger(soap, &soap_tmp_ns__GetCANTrigger, "ns:GetCANTrigger", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetCANTrigger(soap, soap_tmp_ns__GetCANTrigger.boardAddress, settings);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__CANTriggerSettings(soap, &settings);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__CANTriggerSettings(soap, &settings, "ns:CANTriggerSettings", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__CANTriggerSettings(soap, &settings, "ns:CANTriggerSettings", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetAllCurrentAssociations(struct soap *soap)
{	struct ns__GetAllCurrentAssociations soap_tmp_ns__GetAllCurrentAssociations;
	struct ns__GetAllCurrentAssociationsResponse soap_tmp_ns__GetAllCurrentAssociationsResponse;
	soap_default_ns__GetAllCurrentAssociationsResponse(soap, &soap_tmp_ns__GetAllCurrentAssociationsResponse);
	soap_default_ns__GetAllCurrentAssociations(soap, &soap_tmp_ns__GetAllCurrentAssociations);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetAllCurrentAssociations(soap, &soap_tmp_ns__GetAllCurrentAssociations, "ns:GetAllCurrentAssociations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetAllCurrentAssociations(soap, soap_tmp_ns__GetAllCurrentAssociationsResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetAllCurrentAssociationsResponse(soap, &soap_tmp_ns__GetAllCurrentAssociationsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetAllCurrentAssociationsResponse(soap, &soap_tmp_ns__GetAllCurrentAssociationsResponse, "ns:GetAllCurrentAssociationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetAllCurrentAssociationsResponse(soap, &soap_tmp_ns__GetAllCurrentAssociationsResponse, "ns:GetAllCurrentAssociationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetAllPreviousAssociations(struct soap *soap)
{	struct ns__GetAllPreviousAssociations soap_tmp_ns__GetAllPreviousAssociations;
	struct ns__GetAllPreviousAssociationsResponse soap_tmp_ns__GetAllPreviousAssociationsResponse;
	soap_default_ns__GetAllPreviousAssociationsResponse(soap, &soap_tmp_ns__GetAllPreviousAssociationsResponse);
	soap_default_ns__GetAllPreviousAssociations(soap, &soap_tmp_ns__GetAllPreviousAssociations);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetAllPreviousAssociations(soap, &soap_tmp_ns__GetAllPreviousAssociations, "ns:GetAllPreviousAssociations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetAllPreviousAssociations(soap, soap_tmp_ns__GetAllPreviousAssociations.currentMeasurementNumber, soap_tmp_ns__GetAllPreviousAssociationsResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetAllPreviousAssociationsResponse(soap, &soap_tmp_ns__GetAllPreviousAssociationsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetAllPreviousAssociationsResponse(soap, &soap_tmp_ns__GetAllPreviousAssociationsResponse, "ns:GetAllPreviousAssociationsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetAllPreviousAssociationsResponse(soap, &soap_tmp_ns__GetAllPreviousAssociationsResponse, "ns:GetAllPreviousAssociationsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SetAssociations(struct soap *soap)
{	struct ns__SetAssociations soap_tmp_ns__SetAssociations;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__SetAssociations(soap, &soap_tmp_ns__SetAssociations);
	soap->encodingStyle = "";
	if (!soap_get_ns__SetAssociations(soap, &soap_tmp_ns__SetAssociations, "ns:SetAssociations", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SetAssociations(soap, soap_tmp_ns__SetAssociations.associations, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetGPSLogList(struct soap *soap)
{	struct ns__GetGPSLogList soap_tmp_ns__GetGPSLogList;
	struct ns__GetGPSLogListResponse soap_tmp_ns__GetGPSLogListResponse;
	soap_default_ns__GetGPSLogListResponse(soap, &soap_tmp_ns__GetGPSLogListResponse);
	soap_default_ns__GetGPSLogList(soap, &soap_tmp_ns__GetGPSLogList);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetGPSLogList(soap, &soap_tmp_ns__GetGPSLogList, "ns:GetGPSLogList", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetGPSLogList(soap, soap_tmp_ns__GetGPSLogList.from, soap_tmp_ns__GetGPSLogList.to, soap_tmp_ns__GetGPSLogListResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetGPSLogListResponse(soap, &soap_tmp_ns__GetGPSLogListResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetGPSLogListResponse(soap, &soap_tmp_ns__GetGPSLogListResponse, "ns:GetGPSLogListResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetGPSLogListResponse(soap, &soap_tmp_ns__GetGPSLogListResponse, "ns:GetGPSLogListResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__WriteDev(struct soap *soap)
{	struct ns__WriteDev soap_tmp_ns__WriteDev;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__WriteDev(soap, &soap_tmp_ns__WriteDev);
	soap->encodingStyle = "";
	if (!soap_get_ns__WriteDev(soap, &soap_tmp_ns__WriteDev, "ns:WriteDev", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__WriteDev(soap, soap_tmp_ns__WriteDev.boardAddress, soap_tmp_ns__WriteDev.type, soap_tmp_ns__WriteDev.data, soap_tmp_ns__WriteDev.aux1, soap_tmp_ns__WriteDev.aux2, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__ReadDev(struct soap *soap)
{	struct ns__ReadDev soap_tmp_ns__ReadDev;
	struct ns__ReadDevResponse soap_tmp_ns__ReadDevResponse;
	soap_default_ns__ReadDevResponse(soap, &soap_tmp_ns__ReadDevResponse);
	soap_default_ns__ReadDev(soap, &soap_tmp_ns__ReadDev);
	soap->encodingStyle = "";
	if (!soap_get_ns__ReadDev(soap, &soap_tmp_ns__ReadDev, "ns:ReadDev", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__ReadDev(soap, soap_tmp_ns__ReadDev.boardAddress, soap_tmp_ns__ReadDev.type, soap_tmp_ns__ReadDev.count, soap_tmp_ns__ReadDev.aux1, soap_tmp_ns__ReadDev.aux2, soap_tmp_ns__ReadDevResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__ReadDevResponse(soap, &soap_tmp_ns__ReadDevResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__ReadDevResponse(soap, &soap_tmp_ns__ReadDevResponse, "ns:ReadDevResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__ReadDevResponse(soap, &soap_tmp_ns__ReadDevResponse, "ns:ReadDevResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__ReadWriteTwi(struct soap *soap)
{	struct ns__ReadWriteTwi soap_tmp_ns__ReadWriteTwi;
	struct ns__ReadWriteTwiResponse soap_tmp_ns__ReadWriteTwiResponse;
	soap_default_ns__ReadWriteTwiResponse(soap, &soap_tmp_ns__ReadWriteTwiResponse);
	soap_default_ns__ReadWriteTwi(soap, &soap_tmp_ns__ReadWriteTwi);
	soap->encodingStyle = "";
	if (!soap_get_ns__ReadWriteTwi(soap, &soap_tmp_ns__ReadWriteTwi, "ns:ReadWriteTwi", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__ReadWriteTwi(soap, soap_tmp_ns__ReadWriteTwi.boardAddress, soap_tmp_ns__ReadWriteTwi.amplifier, soap_tmp_ns__ReadWriteTwi.data, soap_tmp_ns__ReadWriteTwiResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__ReadWriteTwiResponse(soap, &soap_tmp_ns__ReadWriteTwiResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__ReadWriteTwiResponse(soap, &soap_tmp_ns__ReadWriteTwiResponse, "ns:ReadWriteTwiResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__ReadWriteTwiResponse(soap, &soap_tmp_ns__ReadWriteTwiResponse, "ns:ReadWriteTwiResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__PrepareStart(struct soap *soap)
{	struct ns__PrepareStart soap_tmp_ns__PrepareStart;
	struct ns__PrepareStartResponse soap_tmp_ns__PrepareStartResponse;
	double soap_tmp_double;
	soap_default_ns__PrepareStartResponse(soap, &soap_tmp_ns__PrepareStartResponse);
	soap_default_double(soap, &soap_tmp_double);
	soap_tmp_ns__PrepareStartResponse.delayTime = &soap_tmp_double;
	soap_default_ns__PrepareStart(soap, &soap_tmp_ns__PrepareStart);
	soap->encodingStyle = "";
	if (!soap_get_ns__PrepareStart(soap, &soap_tmp_ns__PrepareStart, "ns:PrepareStart", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__PrepareStart(soap, &soap_tmp_double);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__PrepareStartResponse(soap, &soap_tmp_ns__PrepareStartResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__PrepareStartResponse(soap, &soap_tmp_ns__PrepareStartResponse, "ns:PrepareStartResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__PrepareStartResponse(soap, &soap_tmp_ns__PrepareStartResponse, "ns:PrepareStartResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SetStartInfo(struct soap *soap)
{	struct ns__SetStartInfo soap_tmp_ns__SetStartInfo;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__SetStartInfo(soap, &soap_tmp_ns__SetStartInfo);
	soap->encodingStyle = "";
	if (!soap_get_ns__SetStartInfo(soap, &soap_tmp_ns__SetStartInfo, "ns:SetStartInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SetStartInfo(soap, soap_tmp_ns__SetStartInfo.startTime, soap_tmp_ns__SetStartInfo.measurementNr, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__ExecuteCommand(struct soap *soap)
{	struct ns__ExecuteCommand soap_tmp_ns__ExecuteCommand;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__ExecuteCommand(soap, &soap_tmp_ns__ExecuteCommand);
	soap->encodingStyle = "";
	if (!soap_get_ns__ExecuteCommand(soap, &soap_tmp_ns__ExecuteCommand, "ns:ExecuteCommand", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__ExecuteCommand(soap, soap_tmp_ns__ExecuteCommand.command, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__StartCalibration(struct soap *soap)
{	struct ns__StartCalibration soap_tmp_ns__StartCalibration;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__StartCalibration(soap, &soap_tmp_ns__StartCalibration);
	soap->encodingStyle = "";
	if (!soap_get_ns__StartCalibration(soap, &soap_tmp_ns__StartCalibration, "ns:StartCalibration", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__StartCalibration(soap, soap_tmp_ns__StartCalibration.type, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetStatus(struct soap *soap)
{	struct ns__GetStatus soap_tmp_ns__GetStatus;
	struct ns__Status status;
	soap_default_ns__Status(soap, &status);
	soap_default_ns__GetStatus(soap, &soap_tmp_ns__GetStatus);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetStatus(soap, &soap_tmp_ns__GetStatus, "ns:GetStatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetStatus(soap, status);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__Status(soap, &status);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__Status(soap, &status, "ns:Status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__Status(soap, &status, "ns:Status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__WaitForStatusChange(struct soap *soap)
{	struct ns__WaitForStatusChange soap_tmp_ns__WaitForStatusChange;
	struct ns__Status status;
	soap_default_ns__Status(soap, &status);
	soap_default_ns__WaitForStatusChange(soap, &soap_tmp_ns__WaitForStatusChange);
	soap->encodingStyle = "";
	if (!soap_get_ns__WaitForStatusChange(soap, &soap_tmp_ns__WaitForStatusChange, "ns:WaitForStatusChange", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__WaitForStatusChange(soap, soap_tmp_ns__WaitForStatusChange.eventCounter, status);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__Status(soap, &status);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__Status(soap, &status, "ns:Status", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__Status(soap, &status, "ns:Status", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__LeaveWaitStatus(struct soap *soap)
{	struct ns__LeaveWaitStatus soap_tmp_ns__LeaveWaitStatus;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__LeaveWaitStatus(soap, &soap_tmp_ns__LeaveWaitStatus);
	soap->encodingStyle = "";
	if (!soap_get_ns__LeaveWaitStatus(soap, &soap_tmp_ns__LeaveWaitStatus, "ns:LeaveWaitStatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__LeaveWaitStatus(soap, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetMetadata(struct soap *soap)
{	struct ns__GetMetadata soap_tmp_ns__GetMetadata;
	struct ns__GetMetadataResponse soap_tmp_ns__GetMetadataResponse;
	soap_default_ns__GetMetadataResponse(soap, &soap_tmp_ns__GetMetadataResponse);
	soap_default_ns__GetMetadata(soap, &soap_tmp_ns__GetMetadata);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetMetadata(soap, &soap_tmp_ns__GetMetadata, "ns:GetMetadata", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetMetadata(soap, soap_tmp_ns__GetMetadata.currentMeasurementNumber, soap_tmp_ns__GetMetadata.boardAddress, soap_tmp_ns__GetMetadata.blockFrom, soap_tmp_ns__GetMetadata.blockTo, soap_tmp_ns__GetMetadataResponse.metadata);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetMetadataResponse(soap, &soap_tmp_ns__GetMetadataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetMetadataResponse(soap, &soap_tmp_ns__GetMetadataResponse, "ns:GetMetadataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetMetadataResponse(soap, &soap_tmp_ns__GetMetadataResponse, "ns:GetMetadataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetAllYMetadata(struct soap *soap)
{	struct ns__GetAllYMetadata soap_tmp_ns__GetAllYMetadata;
	struct ns__GetAllYMetadataResponse soap_tmp_ns__GetAllYMetadataResponse;
	soap_default_ns__GetAllYMetadataResponse(soap, &soap_tmp_ns__GetAllYMetadataResponse);
	soap_default_ns__GetAllYMetadata(soap, &soap_tmp_ns__GetAllYMetadata);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetAllYMetadata(soap, &soap_tmp_ns__GetAllYMetadata, "ns:GetAllYMetadata", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetAllYMetadata(soap, soap_tmp_ns__GetAllYMetadata.currentMeasurementNumber, soap_tmp_ns__GetAllYMetadataResponse.metadata);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetAllYMetadataResponse(soap, &soap_tmp_ns__GetAllYMetadataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetAllYMetadataResponse(soap, &soap_tmp_ns__GetAllYMetadataResponse, "ns:GetAllYMetadataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetAllYMetadataResponse(soap, &soap_tmp_ns__GetAllYMetadataResponse, "ns:GetAllYMetadataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetData(struct soap *soap)
{	struct ns__GetData soap_tmp_ns__GetData;
	struct ns__GetDataResponse soap_tmp_ns__GetDataResponse;
	soap_default_ns__GetDataResponse(soap, &soap_tmp_ns__GetDataResponse);
	soap_default_ns__GetData(soap, &soap_tmp_ns__GetData);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetData(soap, &soap_tmp_ns__GetData, "ns:GetData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetData(soap, soap_tmp_ns__GetData.currentMeasurementNumber, soap_tmp_ns__GetData.requests, soap_tmp_ns__GetDataResponse.data);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetDataResponse(soap, &soap_tmp_ns__GetDataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetDataResponse(soap, &soap_tmp_ns__GetDataResponse, "ns:GetDataResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetDataResponse(soap, &soap_tmp_ns__GetDataResponse, "ns:GetDataResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SendServerCustomCommand(struct soap *soap)
{	struct ns__SendServerCustomCommand soap_tmp_ns__SendServerCustomCommand;
	struct ns__SendServerCustomCommandResponse soap_tmp_ns__SendServerCustomCommandResponse;
	char * soap_tmp_string;
	soap_default_ns__SendServerCustomCommandResponse(soap, &soap_tmp_ns__SendServerCustomCommandResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__SendServerCustomCommandResponse.result = &soap_tmp_string;
	soap_default_ns__SendServerCustomCommand(soap, &soap_tmp_ns__SendServerCustomCommand);
	soap->encodingStyle = "";
	if (!soap_get_ns__SendServerCustomCommand(soap, &soap_tmp_ns__SendServerCustomCommand, "ns:SendServerCustomCommand", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SendServerCustomCommand(soap, soap_tmp_ns__SendServerCustomCommand.command, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__SendServerCustomCommandResponse(soap, &soap_tmp_ns__SendServerCustomCommandResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__SendServerCustomCommandResponse(soap, &soap_tmp_ns__SendServerCustomCommandResponse, "ns:SendServerCustomCommandResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__SendServerCustomCommandResponse(soap, &soap_tmp_ns__SendServerCustomCommandResponse, "ns:SendServerCustomCommandResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__LoadAutosequence(struct soap *soap)
{	struct ns__LoadAutosequence soap_tmp_ns__LoadAutosequence;
	struct ns__LoadAutosequenceResponse soap_tmp_ns__LoadAutosequenceResponse;
	char * soap_tmp_string;
	soap_default_ns__LoadAutosequenceResponse(soap, &soap_tmp_ns__LoadAutosequenceResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__LoadAutosequenceResponse.result = &soap_tmp_string;
	soap_default_ns__LoadAutosequence(soap, &soap_tmp_ns__LoadAutosequence);
	soap->encodingStyle = "";
	if (!soap_get_ns__LoadAutosequence(soap, &soap_tmp_ns__LoadAutosequence, "ns:LoadAutosequence", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__LoadAutosequence(soap, soap_tmp_ns__LoadAutosequence.Sequence, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__LoadAutosequenceResponse(soap, &soap_tmp_ns__LoadAutosequenceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__LoadAutosequenceResponse(soap, &soap_tmp_ns__LoadAutosequenceResponse, "ns:LoadAutosequenceResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__LoadAutosequenceResponse(soap, &soap_tmp_ns__LoadAutosequenceResponse, "ns:LoadAutosequenceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__StartAutoSequence(struct soap *soap)
{	struct ns__StartAutoSequence soap_tmp_ns__StartAutoSequence;
	struct ns__StartAutoSequenceResponse soap_tmp_ns__StartAutoSequenceResponse;
	char * soap_tmp_string;
	soap_default_ns__StartAutoSequenceResponse(soap, &soap_tmp_ns__StartAutoSequenceResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__StartAutoSequenceResponse.result = &soap_tmp_string;
	soap_default_ns__StartAutoSequence(soap, &soap_tmp_ns__StartAutoSequence);
	soap->encodingStyle = "";
	if (!soap_get_ns__StartAutoSequence(soap, &soap_tmp_ns__StartAutoSequence, "ns:StartAutoSequence", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__StartAutoSequence(soap, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__StartAutoSequenceResponse(soap, &soap_tmp_ns__StartAutoSequenceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__StartAutoSequenceResponse(soap, &soap_tmp_ns__StartAutoSequenceResponse, "ns:StartAutoSequenceResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__StartAutoSequenceResponse(soap, &soap_tmp_ns__StartAutoSequenceResponse, "ns:StartAutoSequenceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__StopAutoSequence(struct soap *soap)
{	struct ns__StopAutoSequence soap_tmp_ns__StopAutoSequence;
	struct ns__StopAutoSequenceResponse soap_tmp_ns__StopAutoSequenceResponse;
	char * soap_tmp_string;
	soap_default_ns__StopAutoSequenceResponse(soap, &soap_tmp_ns__StopAutoSequenceResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns__StopAutoSequenceResponse.result = &soap_tmp_string;
	soap_default_ns__StopAutoSequence(soap, &soap_tmp_ns__StopAutoSequence);
	soap->encodingStyle = "";
	if (!soap_get_ns__StopAutoSequence(soap, &soap_tmp_ns__StopAutoSequence, "ns:StopAutoSequence", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__StopAutoSequence(soap, &soap_tmp_string);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__StopAutoSequenceResponse(soap, &soap_tmp_ns__StopAutoSequenceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__StopAutoSequenceResponse(soap, &soap_tmp_ns__StopAutoSequenceResponse, "ns:StopAutoSequenceResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__StopAutoSequenceResponse(soap, &soap_tmp_ns__StopAutoSequenceResponse, "ns:StopAutoSequenceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetAutoSequence(struct soap *soap)
{	struct ns__GetAutoSequence soap_tmp_ns__GetAutoSequence;
	struct ns__GetAutoSequenceResponse soap_tmp_ns__GetAutoSequenceResponse;
	soap_default_ns__GetAutoSequenceResponse(soap, &soap_tmp_ns__GetAutoSequenceResponse);
	soap_default_ns__GetAutoSequence(soap, &soap_tmp_ns__GetAutoSequence);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetAutoSequence(soap, &soap_tmp_ns__GetAutoSequence, "ns:GetAutoSequence", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetAutoSequence(soap, soap_tmp_ns__GetAutoSequenceResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetAutoSequenceResponse(soap, &soap_tmp_ns__GetAutoSequenceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetAutoSequenceResponse(soap, &soap_tmp_ns__GetAutoSequenceResponse, "ns:GetAutoSequenceResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetAutoSequenceResponse(soap, &soap_tmp_ns__GetAutoSequenceResponse, "ns:GetAutoSequenceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SetDeviceSettings(struct soap *soap)
{	struct ns__SetDeviceSettings soap_tmp_ns__SetDeviceSettings;
	struct ns__DummyResponse dummyOut;
	soap_default_ns__DummyResponse(soap, &dummyOut);
	soap_default_ns__SetDeviceSettings(soap, &soap_tmp_ns__SetDeviceSettings);
	soap->encodingStyle = "";
	if (!soap_get_ns__SetDeviceSettings(soap, &soap_tmp_ns__SetDeviceSettings, "ns:SetDeviceSettings", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SetDeviceSettings(soap, soap_tmp_ns__SetDeviceSettings.Settings, &dummyOut);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__DummyResponse(soap, &dummyOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__DummyResponse(soap, &dummyOut, "ns:DummyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetFreeDiskSpace(struct soap *soap)
{	struct ns__GetFreeDiskSpace soap_tmp_ns__GetFreeDiskSpace;
	ns__DiskSpace DiskSpace;
	DiskSpace.soap_default(soap);
	soap_default_ns__GetFreeDiskSpace(soap, &soap_tmp_ns__GetFreeDiskSpace);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetFreeDiskSpace(soap, &soap_tmp_ns__GetFreeDiskSpace, "ns:GetFreeDiskSpace", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetFreeDiskSpace(soap, DiskSpace);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	DiskSpace.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || DiskSpace.soap_put(soap, "ns:DiskSpace", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || DiskSpace.soap_put(soap, "ns:DiskSpace", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetMACAddress(struct soap *soap)
{	struct ns__GetMACAddress soap_tmp_ns__GetMACAddress;
	struct ns__GetMACAddressResponse soap_tmp_ns__GetMACAddressResponse;
	soap_default_ns__GetMACAddressResponse(soap, &soap_tmp_ns__GetMACAddressResponse);
	soap_default_ns__GetMACAddress(soap, &soap_tmp_ns__GetMACAddress);
	soap->encodingStyle = "";
	if (!soap_get_ns__GetMACAddress(soap, &soap_tmp_ns__GetMACAddress, "ns:GetMACAddress", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetMACAddress(soap, soap_tmp_ns__GetMACAddress.IPAddress, soap_tmp_ns__GetMACAddressResponse.MACAddress);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__GetMACAddressResponse(soap, &soap_tmp_ns__GetMACAddressResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetMACAddressResponse(soap, &soap_tmp_ns__GetMACAddressResponse, "ns:GetMACAddressResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetMACAddressResponse(soap, &soap_tmp_ns__GetMACAddressResponse, "ns:GetMACAddressResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

/* End of soapServer.cpp */
