# ccache support for faster rebuilds
if(NOT DEFINED USE_CCACHE)
    set(USE_CCACHE ON CACHE BOOL "Use ccache if available")
endif()

if(USE_CCACHE)
    find_program(CCACHE_PROGRAM ccache)
    if(CCACHE_PROGRAM)
        message(STATUS "Found ccache: ${CCACHE_PROGRAM}")
        set(CMAKE_C_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
        set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
    else()
        message(STATUS "ccache not found, building without cache")
    endif()
endif()